services:
  rooms:
    build:
      context: .
      dockerfile: ./apps/rooms/Dockerfile
      target: development
    command: yarn start:dev rooms
    env_file:
      - ./apps/rooms/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo