services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn start:dev auth
    env_file:
      - ./.env/.auth.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
  rooms:
    build:
      context: .
      dockerfile: ./apps/rooms/Dockerfile
      target: development
    command: yarn start:dev rooms
    env_file:
      - ./.env/.rooms.env
    ports:
      - '3004:3004'
    volumes:
      - .:/usr/src/app
  records:
    build:
      context: .
      dockerfile: ./apps/records/Dockerfile
      target: development
    command: yarn start:dev records
    env_file:
      - ./.env/.records.env
    ports:
      - '3006:3006'
    volumes:
      - .:/usr/src/app